apiVersion: apps/v1
kind: Deployment
metadata:
  name: weedweek-gatsby
  namespace: sites
  labels:
    app:  weedweek-gatsby
spec:
  selector:
    matchLabels:
      app: weedweek-gatsby
  replicas: 1
  template:
    metadata:
      labels:
        app: weedweek-gatsby
    spec:
      containers:
      - name: weedweek-gatsby
        image: hub.ivan.pl/weedweek-gatsby:1
        ports:
        - containerPort:  80
          name: weedweek-gatsby
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: weedweek-gatsby
  namespace: sites
spec:
  selector:
    app: weedweek-gatsby
  type: ClusterIP
  ports:
  - name: weedweek-gatsby
    protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: weedweek-gatsby
  namespace: sites
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
      - weedweek.ivan.pl
    secretName: weedweek-gatsby-tls
  rules:
  - host: weedweek.ivan.pl
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: weedweek-gatsby
            port:
              number: 80